version: '3.1'

services:

  consignment-cli:
    build: ./shippy-cli-consignment
    networks:
      - shippy-backend-tier
      - consignment-tier

  consignment-service:
    build: ./shippy-service-consignment
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    networks:
      - shippy-backend-tier
      - consignment-tier

  vessel-service:
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "mongodb://datastore:27017"
    networks:
      - shippy-backend-tier
      - consignment-tier

  datastore:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    networks:
      - consignment-tier

networks:
  consignment-tier:
  shippy-backend-tier:
